### ISSUE TITLE
Incorrect highlights on get method errors.

### ISSUE THREAD

**Issue by alexflav23** [codacy/codacy-scalameta#12]
Hi,

Moving this issue over from the wrong repository.

The Scala analyser is trying to fight again method calls to `Option.get` as well as prefixing methods with `get$Name`, effectively preventing java-esque accessors like `getUser`, `getName` etc. But the current checker introduces a subtle bug.

There are valid usages of `get` against certain objects who neither prefix nor have anything to do with the `Option` type. One neat trick you could employ is:

- If the method call is on `get` but there are no parens used, this could be an `Option`. Because `Option` defines `get` as `def get: T` with no parantheses, calling `get()` with parentheses on an `Option` will not compile. 

- If the method call is on `get` but there *are* parentheses used, you should not be flagging this at all. If the method name is just `def get()` this doesn't void any known Scala style rules.

- If the method name simply *includes* get, like `getName` or `getUser`, flag it as useless prefixing, according to the Twitter Scala style guidelines which you are currently citing. Right now, the middle case can easily fall in either case 1 or case 3 because the checker does not look at the rest of the signature of a `get` method defined, instead it simply checks if the name *includes* get, instead of checking the full name of the method, checking what params are provided, etc.

**Comment by johannegger** [comment]
Hi @alexflav23, thank you for your feedback! 

I'm afraid I don't fully understand your problem. Could you provide a code example showing what's currently not working for you? 
I think you are referencing 2 different Rules:

- method definitions that are prefixed with get (java-like)

- method calls to dangerous .get on Option types

**Comment by alexflav23** [comment]
Hi @johannegger,

I'm obviously suggesting there are issues with both :) and that your analyser confuses the 2 cases.
