### ISSUE TITLE
Imports should not always be grouped together, macro contexts are an exception

### ISSUE THREAD

**Issue by alexflav23** [codacy/codacy-scalameta#26]
### Scala Version (2.10.6 / 2.11.8 / 2.12.1)

This problem is consistent across Scala versions which makes sense because the library used is designed for cross version compatibility.

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

```
Darwin Flavians-iMac 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

### Library Dependencies

This is a general issue where the static analysis tools incorrectly suggests imports should be grouped together in situations where it is not possible to group imports together, such as when importing object contents from an object passed in through a method.

Creating a macro in Scala introduces such a problem every time, because the relevant API is imported from the `c` or `context` value passed in as a parameter. There is no alternative to this DSL, other than explicitly referring to inner objects using `c.universe.FullName`.

```scala
def materialize[T : c.WeakTypeTag](val c: blackbox.Context)
```

```scala
libraryDependencies ++= Seq(
  "org.typelevel" %% "macro-compat" % Versions.macrocompat,
)
```

### Expected Behaviour

Please describe the expected behaviour of the issue, starting from the first action.

1. Create a macro  implementation using macrocompat.
2. Pass in a macro context the default way.
3. Import `c.universe._` contents without getting any kind of "your imports should be grouped together" problem.

### Actual Behaviour

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "there is a false positive on the pattern X in this piece of code: (...)." Copy and paste logs, and include any URLs that you may find useful. 

1. Create any kind of class definition and whatnot containing either type aliases or implicits.
2. Pass an instance of said class as a method parameter.
3. Be able to import the contents of `clz: CustomClass` with `import clz._` without being warned that imports must be grouped together.

### Reproducible Test Case

Any usage of macrocompat will lead to said issue. Such an example can be found [here](https://github.com/outworkers/phantom/blob/develop/phantom-dsl/src/main/scala/com/outworkers/phantom/macros/DatabaseHelper.scala#L36), in a project where we rely heavily on both Codacy for codebase hygiene and macrocompat to offer a consistent product for the largest possible Scala audience, so therefor cross-version.

**Comment by ljmf00** [comment]
I tried to replicate the issue using unittesting and it seems working as expected. I also checked out [outworkers/phantom][1] at codacy, [here][2], I just realized you are using ScalaStyle instead of ScalaMeta. Probably its a false positive from ScalaStyle. Check out their [issue tracker][3].

[1]: https://github.com/outworkers/phantom
[2]: https://app.codacy.com/app/flavian/phantom/file/35567779102/issues/source?bid=2847375&fileBranchId=2847375
[3]: https://github.com/scalastyle/scalastyle/issues
