### ISSUE TITLE
Unable to ignore the `type` keyword from 'Avoid using reserved keywords' pattern

### ISSUE THREAD

**Issue by garethallenstringer** [codacy/codacy-scalameta#36]
### Scala Version (2.10.x / etc)
2.12.6

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.14

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

### Expected Behaviour
1. Adding [`type`] or ['type'] or ["type"] or [type] or ["`type`"] or ['`type`'] to the 'Set of reserved keywords excluded from the search' field to ignore this pattern during analysis
2. No new issues to be added when `type` is used

### Actual Behaviour
1. Adding [`type`] or ['type'] or ["type"] or [type] or ["`type`"] or ['`type`'] to the 'Set of reserved keywords excluded from the search' field to ignore this pattern during analysis
2. Issues are not resolved for using `type`

**Comment by ljmf00** [comment]
I can't reproduce the issue, because it's working as expected using the tool unittesting and on production. Please make sure you are using ScalaMeta on "Code patterns" configuration panel.
