### ISSUE TITLE
Import at class level

### ISSUE THREAD

**Issue by daniel-shuy** [codacy/codacy-scalameta#37]
When importing at the class level instead of the file level, Codacy complains that all imports should be at the top of the file. This however has different effects. Moving an import to the top of the file will import it for all classes in the file, instead of limiting it to the intended class.

A typical example is importing a companion object in a companion class, eg.

```scala
class Clazz {
  import Clazz._
  // ...
}

object Clazz {
  private val Const = ???
}
```

**Comment by IGFCoimbra** [comment]
Hi @daniel-shuy 

I'm very sorry for the amount of time that it took us to get back to you.

If you are still facing this behavior, can you please reach out to support@codacy.com so we can help you with this?

Regards,
Ivo

**Comment by daniel-shuy** [comment]
Never mind, I have removed the pattern from the configuration instead.
