### ISSUE TITLE
False positive "Usage of get on optional type" when check with .isDefined

### ISSUE THREAD

**Issue by ljmf00** [codacy/codacy-scalameta#50]
Imagine this code:
```scala
        case config if config.language.isEmpty && config.languageOpt.isDefined && !config.forceLanguage =>
          Left(s"Invalid language ${config.languageOpt.get}")
```

**Comment by lolgab** [comment]
Using `isDefined` and `get` is and unchecked operation and is considered an antipattern. The current behavior is the right one. You should manage Option values with high order functions only and then get the value with `getOrElse` or do a side effect with `foreach` at the end.

**Comment by lolgab** [comment]
I'm closing this. In case we want to consider this a false positive we will reopen the issue.
