### ISSUE TITLE
"Prohibit pattern matching without default case" problems

### ISSUE THREAD

**Issue by Lasering** [codacy/codacy-scalameta#63]
### Expected Behavior
The rule "Prohibit pattern matching without default case" should not report offenses in the following cases:

1. The pattern match is an exhaustive match covering all the cases.
2. The pattern match is for a PartialFunction.

### Actual Behavior

The [rule](https://github.com/codacy/codacy-scalameta/blob/master/patterns-base/src/main/scala/codacy/patterns/Custom_Scala_DefaultPatternMatching.scala) tries to handle the above cases, but only very superficially:

1. Cases involving exhaustive match are only checked for Try and Either.
2. Cases involving PartialFunction are only checked against some specific functions like `andThen`, `orElse`, `collect` and `collectFirst`.

### Reproducible Test Case
https://app.codacy.com/manual/IST-DSI/scala-expect/issues/index?bid=2886636

For the file HashCodeEqualsToStringSpec.scala its failing for the exhaustive match.
For the file MapFlatmapTransformSpec.scala its failing for the PartialFunction (the method transform receives two PartialFunctions).

I can make a clean project with examples if necessary.

Scala version 2.13. Arch Linux 5.5.10-arch1-1. OpenJDK 13.0.2.

**Comment by lolgab** [comment]
You are completely true.
Sadly our tool is written on top of Scalameta that can't give us the informations necessary to give correct advises in those cases.
To not delete the rule completely I made it work only for some known standard library cases. So now it will trigger in very few specialized cases, but at least it will not give false positives.
Thank you very much for reporting the problem.
